CREATE SCHEMA IF NOT EXISTS AUXILIAR;
CREATE SCHEMA IF NOT EXISTS CONTATO;
CREATE SCHEMA IF NOT EXISTS PESSOA;
CREATE SCHEMA IF NOT EXISTS LOGRADOURO;
CREATE SCHEMA IF NOT EXISTS ENDERECO;

CREATE SCHEMA IF NOT EXISTS HIBERNATE_DB_AUD;

