package br.com.context.model.tipoensino.enumerator;

public enum TipoEnsinoEnum {
    
    ENSINO_FUNDAMENTAL,
    ENSINO_MEDIO,
    EJA_FUNDAMENTAL_ANOS_INICIAIS,
    EJA_FUNDAMENTAL_ANOS_FINAIS,
    EJA_ENSINO_MEDIO,
    EDUCACAO_INFANTIL,
    EDUCACAO_ESPECIAL_DA,
    EDUCACAO_ESPECIAL_DF,
    DEFICIENCIA_INTELECTUAL,
    EDUCACAO_ESPECIAL_DV,
    CURSO_NORMAL,
    ENSINO_FUNDAMENTAL_DE_9_ANOS,
    ENSINO_DE_LINGUAS,
    DEFICIENCIA_MULTIPLA_DMU,
    PAI_PROGRAMA_DE_ALFABETIZACAO_E_INCLUSAO,
    PEJ_PROJETO_ESCOLA_DA_JUVENTUDE,
    ENSINO_MEDIO_INTEGRADO_A_EDUCACAO_PROFISSIONAL,
    COMPLEMENTACAO_EDUCACIONAL,
    ENSINO_FUNDAMENTAL_N1_PRTE,
    ATIVIDADES_CURRICULARES_DESPORTIVAS_ACD,
    ATENDIMENTO_EDUCACIONAL_ESPECIALIZADO,
    EDUCACAO_ESPECIAL_EXCLUSIVA,
    ESPANHOL,
    EDUCACAO_PROFISSIONAL,
    PROEJA_ENSINO_FUNDAMENTAL,
    PROEJA_ENSINO_MEDIO,
    PROJOVEM_URBANO,
    TRANSTORNO_DO_ESPECTRO_DO_AUTISMO,
    ENSINO_FUNDAMENTAL_N2_PRTE,
    EJA_TECNICO_INTEGRADO_COM_A_EDUCACAO_PROFISSIONAL_ENSINO_FUNDAMENTAL,
    EJA_TECNICO_INTEGRADO_COM_A_EDUCACAO_PROFISSIONAL_ENSINO_MEDIO,
    ENSINO_MEDIO_N3_PRTE;

}
