INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'John', 'Doe');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Steven', 'Smith');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'Jane', 'Doe');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME) VALUES (4, 'David', 'Williams');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME) VALUES (5, 'Chris', 'Brown');
INSERT INTO CLIENT (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'John', 'Doe');


