version: '3.7'

networks:
  kong-net:

services:
    kong:
      image: kong:latest
      restart: on-failure
      user: "kong"
      environment:
        KONG_DATABASE: "off"
        KONG_DECLARATIVE_CONFIG: kong.yml
        KONG_ADMIN_ACCESS_LOG: /dev/stdout
        KONG_ADMIN_ERROR_LOG: /dev/stderr
        KONG_PROXY_ACCESS_LOG: /dev/stdout
        KONG_PROXY_ERROR_LOG: /dev/stderr
        KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      volumes:
        - ./kong.yml:/kong.yml:ro
      networks:
        - kong-net
      ports:
        - "8000:8000"
        - "8443:8443"
        - "8001:8001"
        - "8444:8444"
        - "8002:8002"
        - "8445:8445"
        - "8003:8003"
        - "8004:8004"
      healthcheck:
        test: [ "CMD", "kong", "health" ]
        interval: 10s
        timeout: 10s
        retries: 10

    konga:
      container_name: konga
      image: pantsel/konga:latest
      restart: on-failure
      networks:
        - kong-net
      ports:
        - "1337:1337"
