version: '3.3'

services:
  spring-boot:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - env=devpppppppppppppppppp
    ports :
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.5'
        reservations:
          memory: 512M
