spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/test
      database: test


#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/admin_company?useSSL=false&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
#    username: root
#    password: root
#    testWhileIdle: true
#    validationQuery: SELECT 1
#
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      hibernate:
#        default_schema: admin_company
#
#
