apiVersion: v1
kind: Service
metadata:
    name: simple-api
    labels:
        app: simple-api
spec:
    type: ClusterIP
    ports:
    - ports: 3000
      targetPort: 3000
    selector:
        app: simple-api
