spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: milenna.psicologia@gmail.com
        password: mil365779
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        enable: false
        test-connection: true
        