version: '3'

#O tempo médio para acessar o phpmyadmin depois de start todos os serviços é de 8 minutos
services:
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mysql
#    command: [mysqld,--default-authentication-plugin=mysql_native_password, --character-set-server=utf8, --collation-server=utf8_bin, --default-storage-engine=INNODB]
#    command: --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: OuPfme45oAM6m6S8lqy4PQfxlYFlCnmPzyaloZ5Zw=
      MYSQL_DATABASE: mydb
#    volumes:
#      - ./docker/mysql:/var/lib/mysql
#      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    networks:
      - network-educa-facil
    expose:
      # Opens port 3306 on the container
      - '3306'
#    deploy:
#      resources:
#        limits:
#          memory: 2048M
#        reservations:
#          memory: 1024M
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "88:80"
    networks:
      - network-educa-facil
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: OuPfme45oAM6m6S8lqy4PQfxlYFlCnmPzyaloZ5Zw=

networks:
  network-educa-facil:
