version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: database_01
    restart: always
    ports:
      - 27017:27017
    network_mode: host
    healthcheck:
      test: "exit 0"