version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
      - "3306:3306"
    volumes:
      - /home/Desenvolvimento/Docker/MySql/Volumes:/var/lib/mysql
