spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1522:orcl
    username: root
    password: root
  jpa:
    database-platform=org: hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
