#spring:
#  datasource:
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@//10.238.2.36:1521/ibi
#      username: usadq
#      password: Alelo_2018
#  jpa:
#    database-platform=org: hibernate.dialect.PostgreSQL9Dialect
#    hibernate:
#      ddl-auto: create-drop
