package br.com.context.model.tipoclasse.numerator;

public enum TipoClasseEnum {
    
    MULTISSERIADA,
    PRESENCA_FLEXIVEL_SEMI_PRESENCIAL,
    ACELERACAO,
    FLEXIBILIZADA,
    RECUPERACAO_DE_CICLO,
    SALA_DE_RECURSO,
    PROGRAMA_PROFISSAO,
    CONVENIADA_APAE,
    RECUPERACAO_DE_CICLO_MISTA,
    PIC_PROJETO_INTENSIVO_NO_CICLO,
    ITINERANTE,
    TELETEC_1,
    TELETEC_2,
    TELECURSO_PRESENCIAL,
    MULTIFUNCIONAL,
    EDUCACAO_PROFISSIONAL_AOS_SABADOS,
    ENSINO_INTEGRAL,
    OUTRO;

}
